version: '3.8'
services:
  psi-eliane:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: lun@dti091282
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080